/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.exp1.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.exp1.exp1.DecVariavel;
import org.xtext.example.exp1.exp1.Exp1;
import org.xtext.example.exp1.exp1.Exp1Factory;
import org.xtext.example.exp1.exp1.Exp1Package;
import org.xtext.example.exp1.exp1.ExpAritmetica;
import org.xtext.example.exp1.exp1.Expressao;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class Exp1PackageImpl extends EPackageImpl implements Exp1Package
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass exp1EClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressaoEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass decVariavelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expAritmeticaEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.exp1.exp1.Exp1Package#eNS_URI
   * @see #init()
   * @generated
   */
  private Exp1PackageImpl()
  {
    super(eNS_URI, Exp1Factory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   * 
   * <p>This method is used to initialize {@link Exp1Package#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static Exp1Package init()
  {
    if (isInited) return (Exp1Package)EPackage.Registry.INSTANCE.getEPackage(Exp1Package.eNS_URI);

    // Obtain or create and register package
    Exp1PackageImpl theExp1Package = (Exp1PackageImpl)(EPackage.Registry.INSTANCE.get(eNS_URI) instanceof Exp1PackageImpl ? EPackage.Registry.INSTANCE.get(eNS_URI) : new Exp1PackageImpl());

    isInited = true;

    // Create package meta-data objects
    theExp1Package.createPackageContents();

    // Initialize created meta-data
    theExp1Package.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theExp1Package.freeze();

  
    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(Exp1Package.eNS_URI, theExp1Package);
    return theExp1Package;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExp1()
  {
    return exp1EClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExp1_Expressoes()
  {
    return (EReference)exp1EClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpressao()
  {
    return expressaoEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getDecVariavel()
  {
    return decVariavelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDecVariavel_Name()
  {
    return (EAttribute)decVariavelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EAttribute getDecVariavel_Value()
  {
    return (EAttribute)decVariavelEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EClass getExpAritmetica()
  {
    return expAritmeticaEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EReference getExpAritmetica_Sequelof()
  {
    return (EReference)expAritmeticaEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Exp1Factory getExp1Factory()
  {
    return (Exp1Factory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    exp1EClass = createEClass(EXP1);
    createEReference(exp1EClass, EXP1__EXPRESSOES);

    expressaoEClass = createEClass(EXPRESSAO);

    decVariavelEClass = createEClass(DEC_VARIAVEL);
    createEAttribute(decVariavelEClass, DEC_VARIAVEL__NAME);
    createEAttribute(decVariavelEClass, DEC_VARIAVEL__VALUE);

    expAritmeticaEClass = createEClass(EXP_ARITMETICA);
    createEReference(expAritmeticaEClass, EXP_ARITMETICA__SEQUELOF);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    decVariavelEClass.getESuperTypes().add(this.getExpressao());
    expAritmeticaEClass.getESuperTypes().add(this.getExpressao());

    // Initialize classes and features; add operations and parameters
    initEClass(exp1EClass, Exp1.class, "Exp1", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExp1_Expressoes(), this.getExpressao(), null, "expressoes", null, 0, -1, Exp1.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressaoEClass, Expressao.class, "Expressao", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(decVariavelEClass, DecVariavel.class, "DecVariavel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDecVariavel_Name(), ecorePackage.getEString(), "name", null, 0, 1, DecVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getDecVariavel_Value(), ecorePackage.getEString(), "value", null, 0, 1, DecVariavel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expAritmeticaEClass, ExpAritmetica.class, "ExpAritmetica", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getExpAritmetica_Sequelof(), this.getDecVariavel(), null, "sequelof", null, 0, 1, ExpAritmetica.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //Exp1PackageImpl
