/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.exp1.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.exp1.exp1.DecVariavel;
import org.xtext.example.exp1.exp1.Exp1Package;
import org.xtext.example.exp1.exp1.ExpAritmetica;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exp Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.exp1.exp1.impl.ExpAritmeticaImpl#getSequelof <em>Sequelof</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExpAritmeticaImpl extends ExpressaoImpl implements ExpAritmetica
{
  /**
   * The cached value of the '{@link #getSequelof() <em>Sequelof</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSequelof()
   * @generated
   * @ordered
   */
  protected DecVariavel sequelof;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpAritmeticaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Exp1Package.Literals.EXP_ARITMETICA;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DecVariavel getSequelof()
  {
    if (sequelof != null && sequelof.eIsProxy())
    {
      InternalEObject oldSequelof = (InternalEObject)sequelof;
      sequelof = (DecVariavel)eResolveProxy(oldSequelof);
      if (sequelof != oldSequelof)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, Exp1Package.EXP_ARITMETICA__SEQUELOF, oldSequelof, sequelof));
      }
    }
    return sequelof;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DecVariavel basicGetSequelof()
  {
    return sequelof;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSequelof(DecVariavel newSequelof)
  {
    DecVariavel oldSequelof = sequelof;
    sequelof = newSequelof;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Exp1Package.EXP_ARITMETICA__SEQUELOF, oldSequelof, sequelof));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Exp1Package.EXP_ARITMETICA__SEQUELOF:
        if (resolve) return getSequelof();
        return basicGetSequelof();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Exp1Package.EXP_ARITMETICA__SEQUELOF:
        setSequelof((DecVariavel)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Exp1Package.EXP_ARITMETICA__SEQUELOF:
        setSequelof((DecVariavel)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Exp1Package.EXP_ARITMETICA__SEQUELOF:
        return sequelof != null;
    }
    return super.eIsSet(featureID);
  }

} //ExpAritmeticaImpl
