/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.exp1.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.exp1.exp1.Exp1Package;
import org.xtext.example.exp1.exp1.Expressao;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ExpressaoImpl extends MinimalEObjectImpl.Container implements Expressao
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpressaoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Exp1Package.Literals.EXPRESSAO;
  }

} //ExpressaoImpl
