/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractExp1ScopeProvider extends DelegatingScopeProvider {
}
