/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.exp1;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.exp1.exp1.Exp1Factory
 * @model kind="package"
 * @generated
 */
public interface Exp1Package extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "exp1";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/exp1/Exp1";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "exp1";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Exp1Package eINSTANCE = org.xtext.example.exp1.exp1.impl.Exp1PackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.exp1.exp1.impl.Exp1Impl <em>Exp1</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.exp1.exp1.impl.Exp1Impl
   * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExp1()
   * @generated
   */
  int EXP1 = 0;

  /**
   * The feature id for the '<em><b>Expressoes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP1__EXPRESSOES = 0;

  /**
   * The number of structural features of the '<em>Exp1</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP1_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.exp1.exp1.impl.ExpressaoImpl <em>Expressao</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.exp1.exp1.impl.ExpressaoImpl
   * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExpressao()
   * @generated
   */
  int EXPRESSAO = 1;

  /**
   * The number of structural features of the '<em>Expressao</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSAO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.exp1.exp1.impl.DecVariavelImpl <em>Dec Variavel</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.exp1.exp1.impl.DecVariavelImpl
   * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getDecVariavel()
   * @generated
   */
  int DEC_VARIAVEL = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEC_VARIAVEL__NAME = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEC_VARIAVEL__VALUE = EXPRESSAO_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Dec Variavel</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEC_VARIAVEL_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.exp1.exp1.impl.ExpAritmeticaImpl <em>Exp Aritmetica</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.exp1.exp1.impl.ExpAritmeticaImpl
   * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExpAritmetica()
   * @generated
   */
  int EXP_ARITMETICA = 3;

  /**
   * The feature id for the '<em><b>Sequelof</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_ARITMETICA__SEQUELOF = EXPRESSAO_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Exp Aritmetica</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXP_ARITMETICA_FEATURE_COUNT = EXPRESSAO_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.exp1.exp1.Exp1 <em>Exp1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp1</em>'.
   * @see org.xtext.example.exp1.exp1.Exp1
   * @generated
   */
  EClass getExp1();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.exp1.exp1.Exp1#getExpressoes <em>Expressoes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressoes</em>'.
   * @see org.xtext.example.exp1.exp1.Exp1#getExpressoes()
   * @see #getExp1()
   * @generated
   */
  EReference getExp1_Expressoes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.exp1.exp1.Expressao <em>Expressao</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expressao</em>'.
   * @see org.xtext.example.exp1.exp1.Expressao
   * @generated
   */
  EClass getExpressao();

  /**
   * Returns the meta object for class '{@link org.xtext.example.exp1.exp1.DecVariavel <em>Dec Variavel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dec Variavel</em>'.
   * @see org.xtext.example.exp1.exp1.DecVariavel
   * @generated
   */
  EClass getDecVariavel();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.exp1.exp1.DecVariavel#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.exp1.exp1.DecVariavel#getName()
   * @see #getDecVariavel()
   * @generated
   */
  EAttribute getDecVariavel_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.exp1.exp1.DecVariavel#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.exp1.exp1.DecVariavel#getValue()
   * @see #getDecVariavel()
   * @generated
   */
  EAttribute getDecVariavel_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.exp1.exp1.ExpAritmetica <em>Exp Aritmetica</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Exp Aritmetica</em>'.
   * @see org.xtext.example.exp1.exp1.ExpAritmetica
   * @generated
   */
  EClass getExpAritmetica();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.exp1.exp1.ExpAritmetica#getSequelof <em>Sequelof</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sequelof</em>'.
   * @see org.xtext.example.exp1.exp1.ExpAritmetica#getSequelof()
   * @see #getExpAritmetica()
   * @generated
   */
  EReference getExpAritmetica_Sequelof();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  Exp1Factory getExp1Factory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.exp1.exp1.impl.Exp1Impl <em>Exp1</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.exp1.exp1.impl.Exp1Impl
     * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExp1()
     * @generated
     */
    EClass EXP1 = eINSTANCE.getExp1();

    /**
     * The meta object literal for the '<em><b>Expressoes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP1__EXPRESSOES = eINSTANCE.getExp1_Expressoes();

    /**
     * The meta object literal for the '{@link org.xtext.example.exp1.exp1.impl.ExpressaoImpl <em>Expressao</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.exp1.exp1.impl.ExpressaoImpl
     * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExpressao()
     * @generated
     */
    EClass EXPRESSAO = eINSTANCE.getExpressao();

    /**
     * The meta object literal for the '{@link org.xtext.example.exp1.exp1.impl.DecVariavelImpl <em>Dec Variavel</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.exp1.exp1.impl.DecVariavelImpl
     * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getDecVariavel()
     * @generated
     */
    EClass DEC_VARIAVEL = eINSTANCE.getDecVariavel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEC_VARIAVEL__NAME = eINSTANCE.getDecVariavel_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DEC_VARIAVEL__VALUE = eINSTANCE.getDecVariavel_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.exp1.exp1.impl.ExpAritmeticaImpl <em>Exp Aritmetica</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.exp1.exp1.impl.ExpAritmeticaImpl
     * @see org.xtext.example.exp1.exp1.impl.Exp1PackageImpl#getExpAritmetica()
     * @generated
     */
    EClass EXP_ARITMETICA = eINSTANCE.getExpAritmetica();

    /**
     * The meta object literal for the '<em><b>Sequelof</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXP_ARITMETICA__SEQUELOF = eINSTANCE.getExpAritmetica_Sequelof();

  }

} //Exp1Package
