/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.exp1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exp Aritmetica</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.exp1.exp1.ExpAritmetica#getSequelof <em>Sequelof</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.exp1.exp1.Exp1Package#getExpAritmetica()
 * @model
 * @generated
 */
public interface ExpAritmetica extends Expressao
{
  /**
   * Returns the value of the '<em><b>Sequelof</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sequelof</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sequelof</em>' reference.
   * @see #setSequelof(DecVariavel)
   * @see org.xtext.example.exp1.exp1.Exp1Package#getExpAritmetica_Sequelof()
   * @model
   * @generated
   */
  DecVariavel getSequelof();

  /**
   * Sets the value of the '{@link org.xtext.example.exp1.exp1.ExpAritmetica#getSequelof <em>Sequelof</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sequelof</em>' reference.
   * @see #getSequelof()
   * @generated
   */
  void setSequelof(DecVariavel value);

} // ExpAritmetica
