/**
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.exp1;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expressao</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.exp1.exp1.Exp1Package#getExpressao()
 * @model
 * @generated
 */
public interface Expressao extends EObject
{
} // Expressao
