/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Exp1StandaloneSetup extends Exp1StandaloneSetupGenerated {

	def static void doSetup() {
		new Exp1StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
