/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.example.exp1.ui.internal.Exp1Activator;

public class Exp1UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Exp1Activator.getInstance().getInjector("org.xtext.example.exp1.Exp1");
	}

}
