/*
 * generated by Xtext 2.9.2
 */
package org.xtext.example.exp1.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class Exp1ProposalProvider extends AbstractExp1ProposalProvider {
}
